workflows:
  default-workflow:
    name: Default Workflow
    scripts:
      - echo "something"
      - echo $FCI_BRANCH
      - |
        if [ "$FCI_BRANCH" != "try_shell_command" ]; then exit 1; fi
      - echo "second echo"
