workflows:
  default-workflow:
    name: Default Workflow
    scripts:
      - echo "some echo"
      - |
        echo "another echo"
        cd nonexistingdirectory || echo "just try"
        echo "echo shouldn't output"
      - echo "another command"
