workflows:
  default-workflow:
    name: Default Workflow
    scripts:
      - echo "something"
      - echo $FCI_BRANCH
      - |
        [[ $FCI_BRANCH != "try_shell_command" ]] && exit 1
      - echo "second echo"
